"""Added image_url to Vehicle and fixed Booking repr

Revision ID: 612160cc66e8
Revises: 0a15abfde958
Create Date: 2025-07-05 23:42:32.599894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612160cc66e8'
down_revision = '0a15abfde958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
