"""Firebase setup complete

Revision ID: a4eb7c135b2b
Revises: 612160cc66e8
Create Date: 2025-07-08 11:44:43.168989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4eb7c135b2b'
down_revision = '612160cc66e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('driver_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('booking_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=128), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint(None, ['firebase_uid'])

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('seats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('transmission')
        batch_op.drop_column('seats')
        batch_op.drop_column('features')
        batch_op.drop_column('image_urls')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('firebase_uid')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('booking_status')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('driver_fee')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
